<a href="https://colab.research.google.com/github/SaiTeja4239/Pytorch1/blob/main/pytorch3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu121


one of the most common error in deep learning :shape learning

In [3]:
#shapes of matrix multiplication
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])

#torch.mm(tensor_A,tensor_B)# torch.mm is the same as torch.matmul
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [4]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the tensor shape issues , we can manipulate the shape of one of our tensors using a transpose

a transpose switches the axes or dimensions of the given tensor

In [7]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [8]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [11]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"original shapes:tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes:tensor_A={tensor_A.shape}(same shape as above),tensor_B.T={tensor_B.shape}")
print(f"Multiplying :{tensor_A.shape} & {tensor_B.T.shape} <- inner dimensions must match")
print("output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\noutput shape:{output.shape}")

original shapes:tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes:tensor_A=torch.Size([3, 2])(same shape as above),tensor_B.T=torch.Size([3, 2])
Multiplying :torch.Size([3, 2]) & torch.Size([2, 3]) <- inner dimensions must match
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape:torch.Size([3, 3])


## Finding min,max,mean,sum,etc(tensor aggregation)

In [21]:
#create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [22]:
#find the min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [23]:
#find the max
torch.max(x),x.max()

(tensor(91), tensor(91))

In [24]:
#find the mean
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [25]:
#find the sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

finding the positional min and max

In [26]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [30]:
#find the position in tensor that has the minimum value with argmin()->returns index position of target where the minimum value occer
x.argmin()

tensor(0)

In [28]:
x[0]

tensor(1)

In [29]:
#find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [31]:
x[9]

tensor(91)

## reshaping, stacking ,squeezing and unsqueezing tensors

reshaping-reshapes an input tensor to a defined shape

view- return a view of an input tensor of certain shape but keep the same memory as the original tensor

stacking-combine multiple tensors on top of each other(vstack) or side by side(hatack)

squeeze-removes all 1 dimensions from a tensor

unsqueeze-add a 1 dimension to a target tensor

permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [33]:
#lets create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [34]:
#Add an extra dimension
x_reshaped= x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [35]:
#change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
#chaging z changes x (becuse a view of a tensor shares teh same memory as tehe original input )
z[:,0]=5
z,x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [39]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [47]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"previous tensor:{x_reshaped}")
print(f"previous shape:{x_reshaped.shape}")
#Remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"New shape:{x_squeezed.shape}")

previous tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape:torch.Size([9])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [48]:
#torch.unsqueeze() - adds a single dimension to a target tensor at specific dim(dimensions)
print(f"previous target: {x_squeezed}")
print(f"previous shape:{x_squeezed.shape}")

#Add n extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape:torch.Size([9])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [49]:
#torch.permute-rearranges the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3)) #[height,width,colour_channels]

#permute the original tensor to rearrange the axis (or dim) order
x_permuted=x_original.permute(2,0,1) #shifts axis 0->1,1->2,2->3

print(f"previous shape :{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

previous shape :torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [51]:
x_original[0,0,0]=728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))