<a href="https://colab.research.google.com/github/SaiTeja4239/Pytorch1/blob/main/Pytorch4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu121


## indexing (selecting data from tensors)

indexing with Pytorch is similar to indexing with Numpy

In [2]:
#create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
#lets index on the middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [6]:
#lets index on teh most inner bracket(last dimension)
x[0][1][1]

tensor(5)

In [7]:
#you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [8]:
#get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [9]:
#get all values of the 0 dimension but only index 1 of 2nd dimension
x[:,1,1]

tensor([5])

In [10]:
#get index 0 of 0th and 1st dimension and ll values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [11]:
#index on x to return 9
print(x[0][2][2])

#index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


## pytorch tensor & numpy

Numpy is a popular scientific puthon numerical computing library.

and becuse of this ,pytorch has functionally to interact with it.

Data in Numpy, want in Pytorch tensor ->torch.from_numpy(ndarray)

pytorch tensor ->Numpy->torch.Tensor.numpy()

In [13]:
#Numpy array to tensor
import torch
import numpy as np

array =np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [16]:
#change the value of array,what will this do to 'tensor'?
array = array +1
array ,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [17]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

in short how a neural network lerans:

start with random numbers->tensor operations->update random nmbers to try nd make them of the data->again->again->again..

to reduce the randomness in neuralnetworks nd pytorch comes the concept of a random seed.

essentially what the random seed does is "flavour " the randomness.


In [19]:
import torch

#create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1941, 0.5550, 0.7895, 0.6840],
        [0.9380, 0.8013, 0.0940, 0.0694],
        [0.0592, 0.8071, 0.4908, 0.2550]])
tensor([[0.5589, 0.0631, 0.8237, 0.9766],
        [0.6928, 0.7364, 0.4418, 0.4451],
        [0.5339, 0.7684, 0.7776, 0.4568]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [20]:
# lets make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_tensor_C=torch.rand(3,4)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


#running tensors and pytorch pbjects on the GPUs
GPUs = faster computation on numbers,

In [23]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
