<a href="https://colab.research.google.com/github/SaiTeja4239/Pytorch1/blob/main/PyTorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu121


Tensor datatypes

In [ ]:
#float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16 )
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor= torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

Getting Info From Tensors

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4715, 0.8211, 0.1414, 0.6969],
        [0.3804, 0.3141, 0.3238, 0.6934],
        [0.4189, 0.1304, 0.5175, 0.8188]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.4715, 0.8211, 0.1414, 0.6969],
        [0.3804, 0.3141, 0.3238, 0.6934],
        [0.4189, 0.1304, 0.5175, 0.8188]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


## manipulating tensors
tensor operations includes:
Addition
Subtraction
Multiplication
Division
Matrix multiplication

In [ ]:
#Create a tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#multiply by 10
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
#substract 10
tensor-10

tensor([ 0, 10, 20])

In [ ]:
# Pytroch in built function
torch.mul(tensor,10)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor,10)

tensor([20, 30, 40])

Matrix Multiplication

Two ways
1. element-wise
2.matrix multiplication(dot product)

In [ ]:
#element wise multipication
print(tensor, "*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals:tensor([100, 400, 900])


In [ ]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [48]:
#matrix multiplication by hand
1*1+2*2+3*3

14

In [50]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(1400)
CPU times: user 1.52 ms, sys: 55 µs, total: 1.58 ms
Wall time: 1.44 ms


In [51]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 662 µs, sys: 0 ns, total: 662 µs
Wall time: 607 µs


tensor(1400)